# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-consul-cm
data:
  metrics.hcl: |
    telemetry{prometheus_retention_time="24h" disable_hostname=true}
  consul-backup-config.yaml: |
    duration: 1m59s
    consulAddress: consul.default.svc.cluster.local:8500
    backupCrName: backup-consul
